puts "angelo".object_id
puts "angelo".object_id
puts "angelo".object_id
puts "angelo".object_id
puts "angelo".object_id
puts "=================="
puts :angelo.object_id
puts :angelo.object_id
puts :angelo.object_id
puts :angelo.object_id